name: Build with Clang and run tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install clang

      - name: Configure CMake
        run: cmake --workflow --preset dev-clang
